# .bashrc

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

export LC_COLLATE="C"
alias ll='ls -alF --group-directories-first'

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

export WORKON_HOME=$HOME/.virtualenvs
source /usr/bin/virtualenvwrapper.sh

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
PS1='\[\e[1;31m\][\u@\h \W]$\[\e[0m\] '
